env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/jsx-runtime
  - plugin:i18next/recommended
  - eslint-config-prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react-hooks
  - react
  - i18next
  - "@typescript-eslint"
  - "react-combo-plugin-v4"
rules:
  "react-combo-plugin-v4/fsd-import-mast-be-from-index":
    - error
  "react-hooks/rules-of-hooks":
    - error
  "react-hooks/exhaustive-deps":
    - error
  "@typescript-eslint/no-empty-function":
    - off
  "@typescript-eslint/no-extra-semi":
    - off
  react/display-name:
    - 0
  linebreak-style:
    - error
    - unix
  "@typescript-eslint/ban-ts-comment":
    - off
  no-mixed-spaces-and-tabs:
    - off
settings:
  react:
    version: detect
