env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/jsx-runtime
  - plugin:i18next/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - i18next
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-empty-function":
    - off
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  "@typescript-eslint/ban-ts-comment":
    - off
  quotes:
    - error
    - double
  semi:
    - error
    - never
settings:
  react:
    version: detect