export { userSliceReducer } from "./model/slice/userSlice"
export type { UserSchema } from "./model/types/userType"
export { getInited } from "./model/selector/getInited"
export { getUser } from "./model/selector/getUser"
export { getUserRole } from "./model/selector/getUser"
export { actions } from "./model/slice/userSlice"
export { Role } from "./model/const/user"
export { getUserId } from "./model/selector/getUser"
export * as initedSelectors from "./model/selector/getInited"
export * as userSelectors from "./model/selector/getUser"
