name: ContinuousIntegration
on: [workflow_dispatch, push]
jobs:
  loki:
    runs-on: ubuntu-latest
    steps:
      - name: clone project
        uses: actions/checkout@v3
      - name: install dep
        run: yarn install
      - name: test ui view screen
        run: npm run loki:ci
      - name: ui test
        run: npm run test
      - name: eslint
        run: npm run eslint
      - name: stylelint
        run: npm run stylelint
